services:
  postgres:
    image: postgres:16-alpine
    container_name: cherdak_hofnarra_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # ports:
    #   - "127.0.0.1:${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cherdak_hofnarra_server
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: ${PORT}
      SERVER_URL: ${SERVER_URL}
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}"
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - server_uploads:/app/public
    command: >
      sh -c "npx prisma db update && npx prisma db sign && npm run start"

volumes:
  pg_data:
  server_uploads: