// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'304f09049cf9a6333feb51b70ab854d2e402593a302908e91155d690ff0cc8a0'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Archive: {
      readonly selfId: CodecTypes['pg/uuid@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly genre: CodecTypes['pg/text@1']['output'] | null;
      readonly director: CodecTypes['pg/text@1']['output'] | null;
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly duration: CodecTypes['pg/int4@1']['output'];
      readonly rating: CodecTypes['pg/text@1']['output'];
      readonly image: CodecTypes['pg/text@1']['output'];
      readonly videos: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
      readonly actors: ReadonlyArray<CodecTypes['pg/uuid@1']['output']>;
    };
    readonly Event: {
      readonly selfId: CodecTypes['pg/uuid@1']['output'];
      readonly performanceId: CodecTypes['pg/uuid@1']['output'];
      readonly activeState: CodecTypes['pg/bool@1']['output'];
      readonly scene: CodecTypes['pg/text@1']['output'];
      readonly date: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Performance: {
      readonly selfId: CodecTypes['pg/uuid@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly genre: CodecTypes['pg/text@1']['output'] | null;
      readonly director: CodecTypes['pg/text@1']['output'] | null;
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly duration: CodecTypes['pg/int4@1']['output'];
      readonly rating: CodecTypes['pg/text@1']['output'];
      readonly image: CodecTypes['pg/text@1']['output'];
    };
    readonly Person: {
      readonly selfId: CodecTypes['pg/uuid@1']['output'];
      readonly orderNo: CodecTypes['pg/int4@1']['output'];
      readonly contactInfo: CodecTypes['pg/text@1']['output'] | null;
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly role: CodecTypes['pg/text@1']['output'] | null;
      readonly image: CodecTypes['pg/text@1']['output'];
    };
    readonly Registration: {
      readonly selfId: CodecTypes['pg/uuid@1']['output'];
      readonly eventId: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly phoneNumber: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Supervisor: {
      readonly selfId: CodecTypes['pg/uuid@1']['output'];
      readonly orderNo: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly role: CodecTypes['pg/text@1']['output'] | null;
      readonly contactInfo: CodecTypes['pg/text@1']['output'] | null;
      readonly image: CodecTypes['pg/text@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Archive: {
      readonly selfId: CodecTypes['pg/uuid@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly genre: CodecTypes['pg/text@1']['input'] | null;
      readonly director: CodecTypes['pg/text@1']['input'] | null;
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly duration: CodecTypes['pg/int4@1']['input'];
      readonly rating: CodecTypes['pg/text@1']['input'];
      readonly image: CodecTypes['pg/text@1']['input'];
      readonly videos: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
      readonly actors: ReadonlyArray<CodecTypes['pg/uuid@1']['input']>;
    };
    readonly Event: {
      readonly selfId: CodecTypes['pg/uuid@1']['input'];
      readonly performanceId: CodecTypes['pg/uuid@1']['input'];
      readonly activeState: CodecTypes['pg/bool@1']['input'];
      readonly scene: CodecTypes['pg/text@1']['input'];
      readonly date: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Performance: {
      readonly selfId: CodecTypes['pg/uuid@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly genre: CodecTypes['pg/text@1']['input'] | null;
      readonly director: CodecTypes['pg/text@1']['input'] | null;
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly duration: CodecTypes['pg/int4@1']['input'];
      readonly rating: CodecTypes['pg/text@1']['input'];
      readonly image: CodecTypes['pg/text@1']['input'];
    };
    readonly Person: {
      readonly selfId: CodecTypes['pg/uuid@1']['input'];
      readonly orderNo: CodecTypes['pg/int4@1']['input'];
      readonly contactInfo: CodecTypes['pg/text@1']['input'] | null;
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly role: CodecTypes['pg/text@1']['input'] | null;
      readonly image: CodecTypes['pg/text@1']['input'];
    };
    readonly Registration: {
      readonly selfId: CodecTypes['pg/uuid@1']['input'];
      readonly eventId: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly phoneNumber: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Supervisor: {
      readonly selfId: CodecTypes['pg/uuid@1']['input'];
      readonly orderNo: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly role: CodecTypes['pg/text@1']['input'] | null;
      readonly contactInfo: CodecTypes['pg/text@1']['input'] | null;
      readonly image: CodecTypes['pg/text@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly archive: {
      readonly actors: ReadonlyArray<CodecTypes['pg/uuid@1']['output']>;
      readonly description: CodecTypes['pg/text@1']['output'];
      readonly director: CodecTypes['pg/text@1']['output'] | null;
      readonly duration: CodecTypes['pg/int4@1']['output'];
      readonly genre: CodecTypes['pg/text@1']['output'] | null;
      readonly image: CodecTypes['pg/text@1']['output'];
      readonly rating: CodecTypes['pg/text@1']['output'];
      readonly selfId: CodecTypes['pg/uuid@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly videos: ReadonlyArray<CodecTypes['pg/text@1']['output']>;
    };
    readonly event: {
      readonly activeState: CodecTypes['pg/bool@1']['output'];
      readonly date: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly performanceId: CodecTypes['pg/uuid@1']['output'];
      readonly scene: CodecTypes['pg/text@1']['output'];
      readonly selfId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly performance: {
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly director: CodecTypes['pg/text@1']['output'] | null;
      readonly duration: CodecTypes['pg/int4@1']['output'];
      readonly genre: CodecTypes['pg/text@1']['output'] | null;
      readonly image: CodecTypes['pg/text@1']['output'];
      readonly rating: CodecTypes['pg/text@1']['output'];
      readonly selfId: CodecTypes['pg/uuid@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
    };
    readonly person: {
      readonly contactInfo: CodecTypes['pg/text@1']['output'] | null;
      readonly image: CodecTypes['pg/text@1']['output'];
      readonly isActive: CodecTypes['pg/bool@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly orderNo: CodecTypes['pg/int4@1']['output'];
      readonly role: CodecTypes['pg/text@1']['output'] | null;
      readonly selfId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly registration: {
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly eventId: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly phoneNumber: CodecTypes['pg/text@1']['output'] | null;
      readonly selfId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly supervisor: {
      readonly contactInfo: CodecTypes['pg/text@1']['output'] | null;
      readonly image: CodecTypes['pg/text@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly orderNo: CodecTypes['pg/int4@1']['output'];
      readonly role: CodecTypes['pg/text@1']['output'] | null;
      readonly selfId: CodecTypes['pg/uuid@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly archive: {
      readonly actors: ReadonlyArray<CodecTypes['pg/uuid@1']['input']>;
      readonly description: CodecTypes['pg/text@1']['input'];
      readonly director: CodecTypes['pg/text@1']['input'] | null;
      readonly duration: CodecTypes['pg/int4@1']['input'];
      readonly genre: CodecTypes['pg/text@1']['input'] | null;
      readonly image: CodecTypes['pg/text@1']['input'];
      readonly rating: CodecTypes['pg/text@1']['input'];
      readonly selfId: CodecTypes['pg/uuid@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly videos: ReadonlyArray<CodecTypes['pg/text@1']['input']>;
    };
    readonly event: {
      readonly activeState: CodecTypes['pg/bool@1']['input'];
      readonly date: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly performanceId: CodecTypes['pg/uuid@1']['input'];
      readonly scene: CodecTypes['pg/text@1']['input'];
      readonly selfId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly performance: {
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly director: CodecTypes['pg/text@1']['input'] | null;
      readonly duration: CodecTypes['pg/int4@1']['input'];
      readonly genre: CodecTypes['pg/text@1']['input'] | null;
      readonly image: CodecTypes['pg/text@1']['input'];
      readonly rating: CodecTypes['pg/text@1']['input'];
      readonly selfId: CodecTypes['pg/uuid@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
    };
    readonly person: {
      readonly contactInfo: CodecTypes['pg/text@1']['input'] | null;
      readonly image: CodecTypes['pg/text@1']['input'];
      readonly isActive: CodecTypes['pg/bool@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly orderNo: CodecTypes['pg/int4@1']['input'];
      readonly role: CodecTypes['pg/text@1']['input'] | null;
      readonly selfId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly registration: {
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly eventId: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly phoneNumber: CodecTypes['pg/text@1']['input'] | null;
      readonly selfId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly supervisor: {
      readonly contactInfo: CodecTypes['pg/text@1']['input'] | null;
      readonly image: CodecTypes['pg/text@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly orderNo: CodecTypes['pg/int4@1']['input'];
      readonly role: CodecTypes['pg/text@1']['input'] | null;
      readonly selfId: CodecTypes['pg/uuid@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly archive: {
              columns: {
                readonly selfId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly genre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly director: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly duration: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly rating: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly image: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly videos: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', readonly []>;
                  };
                };
                readonly actors: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/uuid@1', readonly []>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['selfId']; readonly name: 'Archive_pkey' };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly event: {
              columns: {
                readonly selfId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly performanceId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly activeState: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly scene: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly date: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 3 };
                };
              };
              primaryKey: { readonly columns: readonly ['selfId']; readonly name: 'Event_pkey' };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Event_performanceId_idx';
                  readonly columns: readonly ['performanceId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'event';
                    readonly columns: readonly ['performanceId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'performance';
                    readonly columns: readonly ['selfId'];
                  };
                  readonly name: 'Event_performanceId_fkey';
                },
              ];
            };
            readonly performance: {
              columns: {
                readonly selfId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly genre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly director: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly duration: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly rating: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly image: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['selfId'];
                readonly name: 'Performance_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly person: {
              columns: {
                readonly selfId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly orderNo: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly contactInfo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly isActive: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly image: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['selfId']; readonly name: 'Person_pkey' };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly registration: {
              columns: {
                readonly selfId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly eventId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly phoneNumber: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: {
                readonly columns: readonly ['selfId'];
                readonly name: 'Registration_pkey';
              };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Registration_eventId_idx';
                  readonly columns: readonly ['eventId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'registration';
                    readonly columns: readonly ['eventId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'event';
                    readonly columns: readonly ['selfId'];
                  };
                  readonly name: 'Registration_eventId_fkey';
                },
              ];
            };
            readonly supervisor: {
              columns: {
                readonly selfId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'gen_random_uuid()';
                  };
                };
                readonly orderNo: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly contactInfo: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly image: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: {
                readonly columns: readonly ['selfId'];
                readonly name: 'Supervisor_pkey';
              };
              uniques: readonly [
                { readonly columns: readonly ['name']; readonly name: 'Supervisor_name_key' },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly archive: { readonly namespace: 'public' & NamespaceId; readonly model: 'Archive' };
    readonly performance: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Performance';
    };
    readonly event: { readonly namespace: 'public' & NamespaceId; readonly model: 'Event' };
    readonly person: { readonly namespace: 'public' & NamespaceId; readonly model: 'Person' };
    readonly registration: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Registration';
    };
    readonly supervisor: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Supervisor';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Archive: {
            readonly fields: {
              readonly selfId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly genre: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly director: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly duration: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly rating: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly image: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly videos: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly actors: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
                readonly many: true;
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'archive';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly selfId: { readonly column: 'selfId' };
                readonly title: { readonly column: 'title' };
                readonly genre: { readonly column: 'genre' };
                readonly director: { readonly column: 'director' };
                readonly description: { readonly column: 'description' };
                readonly duration: { readonly column: 'duration' };
                readonly rating: { readonly column: 'rating' };
                readonly image: { readonly column: 'image' };
                readonly videos: { readonly column: 'videos' };
                readonly actors: { readonly column: 'actors' };
              };
            };
          };
          readonly Event: {
            readonly fields: {
              readonly selfId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly performanceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly activeState: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly scene: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly date: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 3 };
                };
              };
            };
            readonly relations: {
              readonly performance: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Performance';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['performanceId'];
                  readonly targetFields: readonly ['selfId'];
                };
              };
              readonly registrations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Registration';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['selfId'];
                  readonly targetFields: readonly ['eventId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'event';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly selfId: { readonly column: 'selfId' };
                readonly performanceId: { readonly column: 'performanceId' };
                readonly activeState: { readonly column: 'activeState' };
                readonly scene: { readonly column: 'scene' };
                readonly date: { readonly column: 'date' };
              };
            };
          };
          readonly Performance: {
            readonly fields: {
              readonly selfId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly genre: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly director: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly duration: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly rating: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly image: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly events: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['selfId'];
                  readonly targetFields: readonly ['performanceId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'performance';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly selfId: { readonly column: 'selfId' };
                readonly title: { readonly column: 'title' };
                readonly genre: { readonly column: 'genre' };
                readonly director: { readonly column: 'director' };
                readonly description: { readonly column: 'description' };
                readonly duration: { readonly column: 'duration' };
                readonly rating: { readonly column: 'rating' };
                readonly image: { readonly column: 'image' };
              };
            };
          };
          readonly Person: {
            readonly fields: {
              readonly selfId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly orderNo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly contactInfo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isActive: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly image: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'person';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly selfId: { readonly column: 'selfId' };
                readonly orderNo: { readonly column: 'orderNo' };
                readonly contactInfo: { readonly column: 'contactInfo' };
                readonly isActive: { readonly column: 'isActive' };
                readonly name: { readonly column: 'name' };
                readonly role: { readonly column: 'role' };
                readonly image: { readonly column: 'image' };
              };
            };
          };
          readonly Registration: {
            readonly fields: {
              readonly selfId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly eventId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly phoneNumber: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly event: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['eventId'];
                  readonly targetFields: readonly ['selfId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'registration';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly selfId: { readonly column: 'selfId' };
                readonly eventId: { readonly column: 'eventId' };
                readonly name: { readonly column: 'name' };
                readonly email: { readonly column: 'email' };
                readonly phoneNumber: { readonly column: 'phoneNumber' };
              };
            };
          };
          readonly Supervisor: {
            readonly fields: {
              readonly selfId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly orderNo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly contactInfo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly image: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'supervisor';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly selfId: { readonly column: 'selfId' };
                readonly orderNo: { readonly column: 'orderNo' };
                readonly name: { readonly column: 'name' };
                readonly role: { readonly column: 'role' };
                readonly contactInfo: { readonly column: 'contactInfo' };
                readonly image: { readonly column: 'image' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
